### ISSUE TITLE
Feature Request: Add debug information to Datalab when downloading data from BigQuery

### ISSUE THREAD

**Issue by parthea** [googledatalab/pydatalab#337]
This is similar to #329. 

I wanted to capture this specific feature request separately because I think it would be helpful to improve the feedback to users when downloading data in Datalab from BigQuery. In particular, it could be helpful to have the following (or similar) debug information to aid in benchmarking / troubleshooting :

- Rows downloaded (eg. x rows downloaded out of 500,000, or % complete) 
- Bytes downloaded
- Time metrics Time elapsed, approximate time remaining)
- Additional BigQuery related debug metrics such as BigQuery Job Id, Creation Time, Start Time, End Time, Bytes Processed, Bytes Billed

This information could be presented as debug to users running in debug mode. Potentially some information could be migrated into the non-debug environment in the future.

**Comment by yebrahim** [comment]
I think this can be very useful, and we might use it as the mechanism to periodically benchmark performance, instead of what each of us did manually in #329.

In fact, I can see this being done generically for any cell that has a long running process. Turning debug info on and off could also be part of individual cell configuration instead of a global thing, and the frontend can pick up that information and decide if showing a progress bar for example would be feasible/useful. The current "infinite" progress bar isn't very useful for long running processes, and can lead to confusion as to whether or not a certain operation got "stuck".

**Comment by parthea** [comment]
Closing as obsolete.
