### ISSUE TITLE
Storage delete operations are not sync

### ISSUE THREAD

**Issue by yebrahim** [googledatalab/pydatalab#344]
As pointed out by @craigcitro, `Object.delete` and `Bucket.delete` actually submit delete jobs to the storage service, so they're not exactly synchronous operations, which is different from user expectations.

We should explore either waiting on the jobs to finish as part of the API itself, or rename these operations to add a `_async` suffix.

**Comment by craigcitro** [comment]
So I think this one's a bit of a gray area: `objects.delete` *itself* is synchronous; the problem is that other operations may not immediately see those updates. In particular, `objects.delete` followed by `buckets.list` seems to fall into the second bullet here:
  https://cloud.google.com/storage/docs/consistency#eventually_consistent_operations

I don't know what the right answer is here; a few ideas:

1. Before we delete the object, we could first find out what bucket it's in, and poll in `_api.objects_delete` to make sure the object has also disappeared from the bucket listing.

2. We could *optionally* poll, say controlled by an argument to `Item.delete`. (There's plenty of room to bikeshed over the default value for that arg. 😁 )

3. We could just warn the user about this in the docs, and update the test.

These basically go in decreasing order of potential slowdown for the user, but also in increasing order of potential for user confusion.

**Comment by chmeyers** [comment]
I believe this behavior is also dependent on whether you are using a Regional storage bucket or a Global one.  Regional buckets should be synchronous, i.e. a delete/add followed by a list() will show consistent behavior.  Global buckets have a delay.
